### ISSUE TITLE
Compilation error on Lubuntu 18.04

### ISSUE THREAD

**Issue by fDyoptric** [nealey/hdjd#12]
Hi ! 

I'm currently trying to make my Hercules DJ Control MP3 e2 works with Mixxx 2.2.0 on Lubuntu 18.04.
I'm new with the use of Linux based OS, and i don't know perfectly how to make everything, so excuse me if i've done a newbie mistake.
So this is my problem:
I have download the zip containing the hdjd-master folder, unzip it in a folder, open my terminal and made this : 
`fdyoptric@fdyoptric-AO725:~$ cd /home/fdyoptric/Téléchargements/hdjd-master
fdyoptric@fdyoptric-AO725:~/Téléchargements/hdjd-master$ make
`
But it said this to me : 
`make: pkg-config: Command not found
cc -Wall -Werror    -c -o usb.o usb.c
usb.c:1:10: fatal error: libusb.h: Aucun fichier ou dossier de ce type
 #include <libusb.h>
          ^~~~~~~~~~
compilation terminated.
<commande interne>: recipe for target 'usb.o' failed
make: *** [usb.o] Error 1
`
So due to my lacuna in Linux OS i'm asking for some help.
Here's a screenshot of the hdjd-master folder after extraction. [https://image.noelshack.com/fichiers/2019/11/2/1552423021-filemanager.png](url)

If you have any suggestion, it will be honestly helping me.
Thank you for your time.
A frenchie.

**Comment by nealey** [comment]
Salut, fDyoptric.

Try running this to install the stuff you need to build:

```bash
sudo apt-get install build-essential
```

**Comment by fDyoptric** [comment]
I've done it : 
`fdyoptric@fdyoptric-AO725:~$ sudo apt-get install build-essential
[sudo] Mot de passe de fdyoptric : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
build-essential est déjà la version la plus récente (12.4ubuntu1).
build-essential passé en « installé manuellement ».
Le paquet suivant a été installé automatiquement et n'est plus nécessaire :
  libllvm6.0
Veuillez utiliser « sudo apt autoremove » pour le supprimer.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 24 non mis à jour.
`
Then done the sudo apt remove : 
`sudo apt autoremove
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Les paquets suivants seront ENLEVÉS :
  libllvm6.0
0 mis à jour, 0 nouvellement installés, 1 à enlever et 24 non mis à jour.
Après cette opération, 61,1 Mo d'espace disque seront libérés.
Souhaitez-vous continuer ? [O/n] O
(Lecture de la base de données... 160134 fichiers et répertoires déjà installés.)
Suppression de libllvm6.0:amd64 (1:6.0-1ubuntu2) ...
Traitement des actions différées (« triggers ») pour libc-bin (2.27-3ubuntu1) ...
`
So it seems to be installed, but, when i'm trying to make the hdjd again, it doesn't change anything : 
`fdyoptric@fdyoptric-AO725:~$ cd /home/fdyoptric/Téléchargements/hdjd-master
fdyoptric@fdyoptric-AO725:~/Téléchargements/hdjd-master$ make
make: pkg-config: Command not found
cc -Wall -Werror    -c -o usb.o usb.c
usb.c:1:10: fatal error: libusb.h: Aucun fichier ou dossier de ce type
 #include <libusb.h>
          ^~~~~~~~~~
compilation terminated.
<commande interne>: recipe for target 'usb.o' failed
make: *** [usb.o] Error 1
`
Thanks for your help!

**Comment by nealey** [comment]
right, you need libusb too. I believe Ubuntu calls it `libusb-dev`

```
sudo apt-get install libusb-dev
```

If that doesn't work, try `libusbx-dev`. It's been a while, I'm not entirely sure. But this is really an Ubuntu question, not a hdjd question.

**Comment by nealey** [comment]
According to #11 you will also need `libasound2-dev`.

Please, when you have it working, list all the packages you had to install, so I can put it on a wiki page and stop getting bug reports from people struggling to build on Ubuntu.

**Comment by fDyoptric** [comment]
I have installed `libusb-dev` and `libasound2-dev`but the compilation seems to still not working.
`fdyoptric@fdyoptric-AO725:~$ cd /home/fdyoptric/Téléchargements/hdjd-master
fdyoptric@fdyoptric-AO725:~/Téléchargements/hdjd-master$ make
make: pkg-config: Command not found
cc -Wall -Werror    -c -o usb.o usb.c
usb.c:1:10: fatal error: libusb.h: Aucun fichier ou dossier de ce type
 #include <libusb.h>
          ^~~~~~~~~~
compilation terminated.
<commande interne>: recipe for target 'usb.o' failed
make: *** [usb.o] Error 1
`
Still not figure how to make it work...
No problem, i'm listing all the the packages since the start :+1:

**Comment by nealey** [comment]
My day job is teaching, so I'm going to turn this around: based on the error message, what package do you suppose you need to install next?

Hint: the build is trying to run a program (command) and saying that it isn't found (installed). 😃

**Comment by nealey** [comment]
Once you have it working, let's see if you can edit Ubuntu build instructions into the README.md file. Then fork this repo, push your changes to Github, and submit a merge request against my tree. When I accept it, your name will be recorded forever as having contributed to hdjd and you will be -= INTERNET FAMOUS =-

**Comment by fDyoptric** [comment]
Hi again ! 
After a few days of test and search, i'm coming back with some question ^^
I've installed pkg config, but a problem remains : `Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing libusb-1.0.pc
to the PKG_CONFIG_PATH environment variable`
So, i've done some search about the PKG_CONFIG_PATH and how to add a library to it. But here's the problem, i've found some topics of people who have the same problem, not with the same library, but i think that it's not a question of a specific library.
So you might ask, why did i not just follow the instruction on the topics, the problem is that the instruction that they say don't work, here is what i've found : 
`PKG_CONFIG_PATH is a environment variable that specifies additional paths in which pkg-config will search for its .pc files.

This variable is used to augment pkg-config's default search path. On a typical Unix system, it will search in the directories /usr/lib/pkgconfig and /usr/share/pkgconfig. This will usually cover system installed modules. However, some local modules may be installed in a different prefix such as /usr/local. In that case, it's necessary to prepend the search path so that pkg-config can locate the .pc files.

The pkg-config program is used to retrieve information about installed libraries in the system. The primary use of pkg-config is to provide the necessary details for compiling and linking a program to a library. This metadata is stored in pkg-config files. These files have the suffix .pc and reside in specific locations known to the pkg-config tool.

To check the PKG_CONFIG_PATH value use this command:

echo $PKG_CONFIG_PATH
To set the PKG_CONFIG_PATH value use:

export PKG_CONFIG_PATH=/usr/lib/pkgconfig
or

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig`

So i've tried to follow those instruction, but nothing seems to work after pressing enter...
If you have any idea, i will help :) Thanks again !

**Comment by nealey** [comment]
Wow, nice work!

I'm going to guess you need the `-dev` package for the library it wants. There may be some other `libusb` package with `-dev` at the end you need. Based on the error message, I'd try `libusb-1.0-dev`.

Honestly you are really far out from the sort of issue it makes sense to work through in the bug tracking system for hdjd. It's fun helping you, but I haven't tried to compile anything on Ubuntu for years now, and you're going to get much better support on an Ubuntu forum. Probably the first response to your post will contain the correct answer, whereas all I can do is guess.
